language: python

before_install:
    - deactivate
    - source devtools/ci/miniconda_install.sh
    - export PYTHONUNBUFFERED=true
    - conda config --set always_yes true
    - conda config channels --add conda-forge
    - conda config channels --add omnia

install:
    # the next two are if the OPS conda build isn't working
    #- source devtools/no-ops-conda/make_build.sh
    #- source devtools/no-ops-conda/build.sh
    # the next three are preferred if the OPS conda build is working
    #- conda build devtools/conda-recipe
    #- conda install --use-local ops_piggybacker-dev
    - curl https://raw.githubusercontent.com/openpathsampling/openpathsampling/master/devtools/conda_ops_dev_install.sh | bash
    - conda install nose python-coveralls

script:
    - conda list
    - python -c "import openpathsampling; print 'OPS version' + openpathsampling.version.full_version"
    - python ops_piggybacker/tests/common_test_data.py
    - nosetests -v --with-coverage

after_success:
    - coveralls

env:
    matrix:
        - CONDA_PY="2.7"
        - CONDA_PY="3.6"
        - CONDA_PY="3.7"
# only run travis on master: either as PR (where the PR tests the merge with
# master) or as a push (where the push is directly to master, as happens
# when a PR is officially merged into master and pushed to GH)
branches:
    only:  
        master
