language: python

before_install:
    - deactivate
    - source devtools/ci/miniconda_install.sh
    - export PYTHONUNBUFFERED=true
    - conda config --set always_yes true
    - conda config --add channels omnia
    - conda config --add channels conda-forge
    - conda create -q -y --name test conda pyyaml pip python=$CONDA_PY
    - source activate test
    - conda config --env --add pinned_packages python=$CONDA_PY

install:
    - curl -OLk https://raw.githubusercontent.com/openpathsampling/openpathsampling/master/devtools/conda_ops_dev_install.sh
    - source conda_ops_dev_install.sh
    - conda install nose coveralls
    - pip install -e .

script:
    - conda list
    - python -c "from __future__ import print_function; import openpathsampling; print('OPS version' + openpathsampling.version.full_version)"
    - python ops_piggybacker/tests/common_test_data.py
    - nosetests -v --with-coverage

after_success:
    - coveralls

env:
    matrix:
        - CONDA_PY="2.7"
        - CONDA_PY="3.6"
        - CONDA_PY="3.7"
# only run travis on master: either as PR (where the PR tests the merge with
# master) or as a push (where the push is directly to master, as happens
# when a PR is officially merged into master and pushed to GH)
branches:
    only:  
        master
