language: python

python:
    - "2.7"

install:
    - deactivate
    - source devtools/ci/install_conda.sh
    - export PYTHONUNBUFFERED=true

script:
    - conda install --yes conda-build
    - conda config --set always_yes true
    # the next two are if the OPS conda build isn't working
    #- source devtools/no-ops-conda/make_build.sh
    #- source devtools/no-ops-conda/build.sh
    # the next three are preferred if the OPS conda build is working
    - conda build devtools/conda-recipe
    - conda install --use-local dynamiq_samplers-dev
    - conda install nose python-coveralls

    - python -c "import openpathsampling; print 'OPS version' + openpathsampling.version.full_version"
    - python ops_piggybacker/tests/common_test_data.py
    - nosetests -v --with-coverage

after_success:
    - coveralls

env:
    matrix:
        - python=2.7 CONDA_PY=27 CONDA_NPY=110
# only run travis on master: either as PR (where the PR tests the merge with
# master) or as a push (where the push is directly to master, as happens
# when a PR is officially merged into master and pushed to GH)
branches:
    only:  
        master
