import openpathsampling as paths

class NoEngine(paths.engines.DynamicsEngine):
    pass

class ShootingStub(paths.pathmover.PathMover):
    def __init__(self, ensemble, selector=None, engine=None):
        super(ShootingStub, self).__init__()
        if engine is None:
            engine = NoEngine()
        if selector is None:
            selector = paths.UniformSelector()  # default
        self.engine = engine
        self.selector = selector
        self.ensemble = ensemble
        self.mimic = paths.OneWayShootingMover(ensemble, selector, engine)


    def move(self, input_sample, trial_trajectory, shooting_point, accepted):
        """Fake a move.

        Parameters
        ----------
        input_sample: :class:`paths.Sample`
            the input sample for this shooting move
        trial_trajectory: :class:`paths.Trajectory`
            the trial trajectory generated by this move
        shooting_point: :class:`paths.Snapshot`
            the shooting point snapshot for this trial
        accepted: bool
            whether the trial was accepted
        """
        initial_trajectory = input_sample.trajectory
        replica = input_sample.replica
        ensemble = input_sample.ensemble

        # determine the direction

        trial_details = paths.SampleDetails(
            initial_trajectory=initial_trajectory,
            shooting_snapshot=shooting_point
        )

        trial = paths.Sample(
            replica=replica,
            trajectory=trial_trajectory,
            ensemble=ensemble,
            parent=input_sample,
            details=trial_details,
            mover=self.mimic
        )

        trials = [trial]
        move_details = paths.MoveDetails()

        if accepted:
            return paths.AcceptedSamplePathMoveChange(
                samples=trials,
                mover=self.mimic,
                details=move_details
            )
        else:
            return paths.RejectedSamplePathMoveChange(
                samples=trial,
                mover=self.mimic,
                details=move_details
            )
