package:
    name: ops_piggybacker
    version: "0.1.0"

source:
    path: ../../

requirements:
    build:
        - python
        - setuptools
        - pyyaml
        - numpy

    run:
        - python
        - numpy
        - scipy
        - pandas
        - openpathsampling

test:
    imports:
        - ops_piggybacker
